### ISSUE TITLE
Tracking issue for REST API implementation

### ISSUE THREAD

**Issue by skyzh** [untitled-group/kanbasu#10]
Currently, we only implement read-only APIs for necessary UI display.

* Required to show basic course information
  - [x] https://oc.sjtu.edu.cn/doc/api/tabs.html (https://github.com/BugenZhao/kanbasu/pull/11)
  - [x] https://oc.sjtu.edu.cn/doc/api/assignments.html (https://github.com/BugenZhao/kanbasu/pull/42)
  - [x] https://oc.sjtu.edu.cn/doc/api/submissions.html (https://github.com/BugenZhao/kanbasu/pull/48)
* Required for canvas_grab core integration
  - [x] https://oc.sjtu.edu.cn/doc/api/modules.html (https://github.com/BugenZhao/kanbasu/pull/23)
  - [x] https://oc.sjtu.edu.cn/doc/api/files.html (https://github.com/BugenZhao/kanbasu/pull/51, https://github.com/BugenZhao/kanbasu/pull/50)
  - [x] https://oc.sjtu.edu.cn/doc/api/folders.html (https://github.com/BugenZhao/kanbasu/pull/62)
  - [x] https://oc.sjtu.edu.cn/doc/api/pages.html (https://github.com/BugenZhao/kanbasu/pull/58)
* Required to post discussions
  - [ ] https://oc.sjtu.edu.cn/doc/api/discussion_topics.html (need post)
* Required to show notifications
  - [x] https://oc.sjtu.edu.cn/doc/api/users.html (include activity stream) (https://github.com/BugenZhao/kanbasu/pull/13)
  - [x] https://oc.sjtu.edu.cn/doc/api/planner.html (https://github.com/BugenZhao/kanbasu/pull/61)
* Others (low priority)
  - [ ] https://oc.sjtu.edu.cn/doc/api/announcements.html
  - [ ] https://oc.sjtu.edu.cn/doc/api/accounts.html (impossible)

If there's any need for new APIs, post new comments below.
